---
config:
  features:
    ADDONS:
      isEnabled: false
    API_GATEWAY:
      isEnabled: true
      selectors:
        - apiGroup: gateway.kyma-project.io
          type: apiGroup
    EVENTING:
      isEnabled: true
      selectors:
        - apiGroup: eventing.kyma-project.io
          type: apiGroup
    EXTENSIBILITY:
      isEnabled: true
    EXTENSIBILITY_WIDGETS:
      isEnabled: false
    EXTERNAL_NODES:
      isEnabled: true
      stage: SECONDARY
    GARDENER_LOGIN:
      isEnabled: false
      kubeconfig: null
    GZIP:
      isEnabled: true
    HIDDEN_NAMESPACES:
      config:
        namespaces:
          - istio-system
          - kube-system
          - kyma-system
      isEnabled: true
    ISTIO:
      isEnabled: true
    JWT_CHECK_CONFIG:
      config:
        issuer: https://kymatest.accounts400.ondemand.com
        jwksUri: https://kymatest.accounts400.ondemand.com/oauth2/certs
      isEnabled: false
    KUBECONFIG_ID:
      config:
        kubeconfigUrl: https://kyma-env-broker.cp.stage.kyma.cloud.sap/kubeconfig
      isEnabled: true
    LEGAL_LINKS:
      config:
        copyright:
          de: https://www.sap.com/corporate/de/legal/copyright.html
          default: https://www.sap.com/corporate/en/legal/copyright.html
        legal-disclosure:
          de: https://www.sap.com/corporate/de/legal/impressum.html
          default: https://www.sap.com/corporate/en/legal/impressum.html
        privacy:
          default: https://help.sap.com/viewer/82bdf2271c6041f79387c122147cf774/Cloud/en-US
        trademark:
          de: https://www.sap.com/corporate/de/legal/trademark.html
          default: https://www.sap.com/corporate/en/legal/trademark.html
    OBSERVABILITY:
      config:
        links:
          - label: Grafana
            path: apis/networking.istio.io/v1beta1/namespaces/kyma-system/virtualservices/monitoring-grafana
          - label: Kiali
            path: apis/networking.istio.io/v1beta1/namespaces/kyma-system/virtualservices/kiali
          - label: Tracing
            path: apis/networking.istio.io/v1beta1/namespaces/kyma-system/virtualservices/tracing
      isEnabled: true
    PROTECTED_RESOURCES:
      config:
        resources:
          - match:
              $.metadata.labels['serverless.kyma-project.io/managed-by']: function-controller
            message: 'Resource managed by: function-controller'
          - match:
              $.metadata.labels['reconciler.kyma-project.io/managed-by']: reconciler
            messageSrc: $.metadata.annotations['reconciler.kyma-project.io/managed-by-reconciler-disclaimer']
          - match:
              $.metadata.labels['istio.io/rev']: default
            message: Resource managed by Istio control plane
          - match:
              $.metadata.labels['applicationconnector.kyma-project.io/managed-by']: compass-runtime-agent
      isEnabled: true
    SENTRY:
      config:
        dsn: https://6b34a073f53c4949bf4f1fae1b788527@o399001.ingest.sentry.io/5953495
      isEnabled: true
      selectors: []
    SERVICE_CATALOG:
      isEnabled: false
    SERVICE_CATALOG_ADDONS:
      isEnabled: false
    SERVICE_CATALOG_READ_ONLY:
      isReadOnly: false
    SHOW_GARDENER_METADATA:
      isEnabled: true
    SHOW_KYMA_VERSION:
      isEnabled: true
    SSO_LOGIN:
      config:
        clientId: e69c0ad6-c283-4baf-9ad7-3714decef49d
        issuerUrl: https://kymatest.accounts400.ondemand.com
        scope: openid
      isEnabled: false
    TRACKING:
      isEnabled: false
  storage: localStorage