FROM eu.gcr.io/kyma-project/busola:${LOCAL_IMAGE}

COPY  --from=extensions-local /build/environments/${ENV}/dist/extensions.yaml /app/core/assets/extensions/extensions.yaml
COPY  ./environments/${ENV}/config.yaml /app/core/assets/config/config.yaml

EXPOSE 3001
ENV NODE_ENV=production ADDRESS=0.0.0.0 IS_DOCKER=true
CMD ["node", "backend-production.js"]
