FROM alpine:3.15.0 AS builder

# declare TARGET_ENV variable and make sure it is passed to build
ARG TARGET_ENV
RUN test -n "$TARGET_ENV" 

WORKDIR /build

RUN apk add --update nodejs npm
RUN apk update && apk upgrade

COPY . /build

RUN npm ci

RUN ENV=${TARGET_ENV} npm run prepare-extensions
RUN ENV=${TARGET_ENV} npm run pack-extensions
