apiVersion: v1
kind: ConfigMap
metadata:
  name: kymas.operator.kyma-project.io
  namespace: kube-public
  labels:
    app.kubernetes.io/name: kymas.operator.kyma-project.io
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |
    moduleTemplates:
      resource:
        kind: ModuleTemplate
        namespace: kyma-system
        group: operator.kyma-project.io
        version: v1alpha1
  details: |
    header: []
    body:
      - name: Summary
        widget: Panel
        children:
          - name: channel
            source: spec.channel
          - name: State
            source: status.state
          - name: Age
            source: metadata.creationTimestamp
      - widget: Table
        source: 'spec.modules[]'
        name: Modules
        visibility: $exists(*)
        children:
          - source: $item.name
            name: Module Name
          - source: $item.channel
            name: Channel
  form: |
    - simple: true
      path: spec.channel
      required: true
    - widget: GenericList
      path: spec.modules
      children:
      - path: "[].name"
        required: true
        enum: '$distinct($moduleTemplates().items.metadata.labels."operator.kyma-project.io/module-name")'
      - path: "[].channel"
        required: true
        visibility: "$boolean($item.name)"
        enum: |
          $filter($moduleTemplates().items, function($v) {
            $v.metadata.labels."operator.kyma-project.io/module-name" = $item.name
          }).spec.channel
  general: |-
    resource:
      kind: Kyma
      group: operator.kyma-project.io
      version: v1alpha1
    name: Kyma
    category: Kyma
    urlPath: kymas
    scope: namespace
  list: |-
    - name: channel
      widget: Labels
      source: spec.channel
    - name: State
      widget: Badge
      source: status.state
      tooltip: status.state
    - name: Age
      source: metadata.creationTimestamp
  translations: |
    en:
      metadata.annotations: Annotations
      metadata.labels: Labels
      metadata.creationTimestamp: Created at
