apiVersion: v1
kind: ConfigMap
metadata:
  name: moduletemplates.operator.kyma-project.io
  namespace: kube-public
  labels:
    app.kubernetes.io/name: moduletemplates.operator.kyma-project.io
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  details: |-
    header: []
    body:
      - name: Summary
        widget: Panel
        visibility: $exists(metadata.annotations."operator.kyma-project.io/doc-url")
        children:
          - name: Channel
            source: spec.channel
            widget: Badge
          - name: 'Documentation'
            widget: ExternalLink
            copyable: false
            source: '"Documentation"'
            link: metadata.annotations."operator.kyma-project.io/doc-url"
      - name: Data
        source: spec.data
        widget: CodeViewer
      - name: Descriptor
        source: spec.descriptor
        widget: CodeViewer
  form: |
    - name: Channel
      path: spec.channel
      simple: true
    - name: Descriptor
      path: spec.descriptor
      widget: CodeEditor
      simple: true
      defaultExpanded: true
      language: '"yaml"'
    - name: Data
      path: spec.data
      widget: CodeEditor
      language: '"yaml"'
  general: |
    resource:
      kind: ModuleTemplate
      group: operator.kyma-project.io
      version: v1beta2
    name: Module Templates
    category: Kyma
    urlPath: moduletemplates
    scope: namespace
    description: >-
      {{[ModuleTemplate Custom Resource](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md)}}
      contains modules' metadata with links to their images and manifests.
  list: |
    - name: Channel
      source: spec.channel
      widget: Badge
