kind: ConfigMap
apiVersion: v1
metadata:
  name: apirules
  namespace: kube-public
  labels:
    app.kubernetes.io/name: apirules
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  dataSources: |-
    relatedGateways:
      resource:
        kind: Gateway
        group: networking.istio.io
        version: v1beta1
        namespace: null
    relatedServices:
      resource:
        kind: Service
        version: v1
        namespace: null
    virtualServices:
      resource:
        kind: VirtualService
        group: networking.istio.io
        version: v1beta1
        namespace: null
      filter: '$contains($item.metadata.ownerReferences[0].name, $root.metadata.name) and $contains($item.metadata.ownerReferences[0].kind, $root.kind)'
  details: |
    header:
      - name: status
        widget: Badge
        highlights:
          positive:
            - 'OK'
          negative:
            - 'ERROR'
          critical:
            - 'SKIPPED'
        source: 'status.APIRuleStatus.code ? status.APIRuleStatus.code : "UNKNOWN"'
        description: status.APIRuleStatus.desc
      - name: host
        source: spec
        widget: APIRuleHost
    body:
      - simple: true
        widget: Alert
        severity: warning
        source: '"alert.spec.jwks_url_http"'
        visibility: '$count(spec.rules.accessStrategies.config.jwks_urls)>0 and $reduce(spec.rules.accessStrategies.config.jwks_urls,function($i, $j){$i or $substringBefore($j,"://")="http"},false)'
      - simple: true
        widget: Alert
        severity: warning
        source: '"alert.spec.trusted_issuers_http"'
        visibility: '$count(spec.rules.accessStrategies.config.trusted_issuers)>0 and $reduce(spec.rules.accessStrategies.config.trusted_issuers,function($i, $j){$i or $substringBefore($j,"://")="http"},false)'
      - name: general
        source: spec
        widget: Panel
        visibility: $exists(spec.timeout)
        children:
        - source: timeout
          name: details.timeout
      - name: service
        source: spec.service
        widget: Panel
        children:
          - name: service.name
            source: name
            widget: ResourceLink
            resource:
              name: $root.spec.service.name
              namespace: $root.metadata.namespace
              kind: '"Service"'
          - name: service.port
            source: port
      - source: spec.rules
        widget: Table
        name: rules
        children:
          - source: $item.path
            name: rules.path
          - source: $item.methods
            name: rules.methods
            widget: Badge
        collapsible:
          - name: general
            source: $item
            widget: Panel
            visibility: $exists($item.timeout)
            children:
            - source: $item.timeout
              name: details.timeout
          - source: $item.accessStrategies
            widget: Table
            disablePadding: true
            name: accessStrategies
            children:
              - source: $item.handler
                name: accessStrategies.handlers
                widget: Badge
              - source: $item.config.required_scope
                name: accessStrategies.required_scope
                widget: JoinedArray
              - source: $item.config.jwks_urls
                name: accessStrategies.jwks_urls
                widget: JoinedArray
              - source: $item.config.trusted_issuers
                name: accessStrategies.trusted_issuers
                widget: JoinedArray
              - source: $item.config.introspection_url
                name: accessStrategies.introspection_url
                widget: Text
              - source: $item.config.introspection_request_headers
                name: accessStrategies.introspection_request_headers
                widget: Labels
              - source: $item.config.token_from
                name: accessStrategies.token_from
                widget: Labels
          - source: $item.mutators
            widget: Table
            disablePadding: true
            name: mutators
            visibility: $exists($item.mutators)
            children:
              - source: $item.handler
                name: mutators.handlers
                widget: Badge
              - source: $item.config
                name: mutators.config
          - name: service
            source: $item.service
            widget: Panel
            visibility: $exists($item.service)
            children:
              - name: service.name
                source: $item.service.name
                widget: ResourceLink
                resource:
                  name: $item.service.name
                  namespace: $root.metadata.namespace
                  kind: '"Service"'
              - name: service.port
                source: $item.service.port
      - widget: ResourceList
        source: $virtualServices()
        name: virtualService
        disableCreate: true
  form: |-
    - simple: true
      required: false
      path: spec.timeout
      name: timeout
      inputInfo: inputInfo.timeout
      value:
        type: number
    - simple: true
      required: false
      path: spec.service
      name: service
      widget: FormGroup
      defaultExpanded: true
      children:
        - simple: true
          required: false
          path: name
          name: service-name
          widget: Resource
          resource:
            kind: Service
            version: v1
            scope: namespace
          trigger: [port]
        - simple: true
          required: false
          path: port
          name: service.port
          subscribe:
            port: "$filter($relatedServices().items, function ($v) { $v.metadata.name = $root.spec.service.name and $v.metadata.namespace = $root.metadata.namespace }).spec.ports[0].port"
    - simple: true
      required: true
      path: spec.gateway
      name: gateway
      widget: ResourceRef
      defaultExpanded: true
      visibility: $canI('networking.istio.io/v1beta1', 'Gateway')
      resource:
        kind: Gateway
        group: networking.istio.io
        version: v1beta1
      overwrite: false
      toInternal:  '($values := $split($, "."); { "namespace": $values[1], "name": $values[0] })'
      toExternal: 'name & "." & namespace & ".svc.cluster.local"'
      trigger: [host]
    - simple: true
      var: separator
      value: ""
    - simple: true
      required: true
      path: spec.gateway
      name: gateway
      visibility: $not($canI('networking.istio.io/v1beta1', 'Gateway'))
      inputInfo: inputInfo.gateway
      overwrite: false
      trigger: [host]
    - simple: true
      required: true
      path: spec.host
      name: host
      enum: "$distinct($filter($relatedGateways().items, function ($v) { $v.metadata.name = $substringBefore($root.spec.gateway, '.') and $v.metadata.namespace = $substringBefore($substringAfter($root.spec.gateway, '.'), '.')}).spec.servers.hosts)"
      subscribe:
        host: "$string($filter($relatedGateways().items, function ($v) {  $v.metadata.name = $substringBefore($root.spec.gateway, '.') and $v.metadata.namespace = $substringBefore($substringAfter($root.spec.gateway, '.'), '.')}).spec.servers[0].hosts[0])"
    - simple: true
      widget: Alert
      severity: error
      alert: '"alert.spec.host"'
      visibility: '$substring(spec.host, 0, 1)="*"'
    - simple: true
      required: true
      path: spec.rules
      name: rules
      widget: GenericList
      defaultExpanded: true
      template:
        path: '/.*'
        methods: ['GET']
        accessStrategies:
          - handler: 'allow'
      children:
        - simple: true
          required: false
          path: '[].timeout'
          name: timeout
          inputInfo: inputInfo.timeout
          value:
            type: number
        - simple: true
          required: true
          path: '[].path'
          name: path
          inputInfo: inputInfo.path
        - required: true
          simple: true
          path: '[].accessStrategies'
          name: accessStrategies
          widget: GenericList
          defaultExpanded: true
          template:
            handler: 'allow'
          children:
            - required: true
              simple: true
              path: '[].handler'
              name: accessStrategies.handler
              enum:
                - allow
                - noop
                - jwt
                - oauth2_introspection
            - path: '[].config'
              simple: true
              name: accessStrategies.config
              type: object
              properties:
                jwks_urls:
                  type: array
                  items:
                    type: string
                    pattern: ^(http://|https://|file://).*$
                trusted_issuers:
                  type: array
                  items:
                    type: string
                    pattern: ^(http://|https://|file://).*$
                required_scope:
                  type: array
                  items:
                    type: string
                introspection_url:
                  type: string
                  pattern: ^(https://|http://).*$
                introspection_request_headers:
                  type: map
                token_from:
                  type: map
              children:
                - simple: true
                  widget: Alert
                  severity: warning
                  alert: '"alert.spec.jwks_url_http"'
                  visibility: '$reduce($item.config.jwks_urls,function($i, $j){$i or $substringBefore($j,"://")="http"},false)'
                - path: jwks_urls
                  name: accessStrategies.jwks_urls
                  inputInfo: inputInfo.jwks_urls
                  simple: true
                  widget: SimpleList
                  visibility: '$item.handler="jwt"'
                  children:
                    - path: '[]'
                      simple: true
                - simple: true
                  widget: Alert
                  severity: warning
                  alert: '"alert.spec.trusted_issuers_http"'
                  visibility: '$reduce($item.config.trusted_issuers,function($i, $j){$i or $substringBefore($j,"://")="http"},false)'
                - path: trusted_issuers
                  name: accessStrategies.trusted_issuers
                  inputInfo: inputInfo.trusted_issuers
                  simple: true
                  widget: SimpleList
                  visibility: '$item.handler="jwt"'
                  children:
                    - path: '[]'
                      simple: true
                - path: introspection_url
                  name: accessStrategies.introspection_url
                  inputInfo: inputInfo.introspection_url
                  simple: true
                  visibility: '$item.handler="oauth2_introspection"'
                - path: introspection_request_headers
                  name: accessStrategies.introspection_request_headers
                  simple: true
                  inputInfo: inputInfo.introspection_request_headers
                  widget: KeyValuePair
                  visibility: '$item.handler="oauth2_introspection"'
                - path: required_scope
                  name: accessStrategies.required_scope
                  simple: true
                  widget: SimpleList
                  visibility: '$item.handler="oauth2_introspection" or $item.handler="oauth2_client_credentials" or $item.handler="jwt"'
                  children:
                    - path: '[]'
                      simple: true
                - path: token_from
                  name: accessStrategies.token_from
                  simple: true
                  inputInfo: inputInfo.token_from
                  widget: KeyValuePair
                  visibility: '$item.handler!="allow" and $item.handler!="noop"'
                  keyEnum:
                  - header
                  - query_parameter
                  - cookie
        - required: true
          simple: true
          path: '[].methods'
          name: rules.methods
          widget: MultiCheckbox
          options:
            - key: GET
            - key: POST
            - key: PUT
            - key: DELETE
            - key: PATCH
            - key: HEAD
        - path: '[].mutators'
          name: mutators
          widget: GenericList
          children:
            - path: '[].config'
              name: accessStrategies.config
              widget: KeyValuePair
            - required: true
              path: '[].handler'
              name: accessStrategies.handler
        - path: '[].service'
          simple: true
          name: service
          widget: FormGroup
          required: false
          children:
            - simple: true
              required: false
              path: name
              name: service-name
              widget: Resource
              resource:
                kind: Service
                version: v1
                scope: namespace
              trigger: [accessStrategyPort]
            - simple: true
              required: false
              path: port
              name: service.port
              subscribe:
                accessStrategyPort: "$filter($relatedServices().items, function ($v) { $v.metadata.name = $item.service.name and $v.metadata.namespace = $root.metadata.namespace }).spec.ports[0].port"
  general: |-
    resource:
      kind: APIRule
      group: gateway.kyma-project.io
      version: v1beta1
    name: API Rules
    category: Discovery and Network
    scope: namespace
    description: '{{[APIRule](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/apix-01-apirule/#documentation-content)}} allows for exposing a service externally.'
    urlPath: apirules
  list: |
    - name: host
      source: spec
      widget: APIRuleHost
    - name: service-name
      source: '$string(spec.service.name) ? ($string(spec.service.name) & " (port: " & $string(spec.service.port) & ")") : ""'
      widget: ResourceLink
      resource:
        name: $root.spec.service.name
        namespace: $root.metadata.namespace
        kind: '"Service"'
    - name: status
      widget: Badge
      highlights:
        positive:
          - 'OK'
        negative:
          - 'ERROR'
        critical:
          - 'SKIPPED'
      source: 'status.APIRuleStatus.code ? status.APIRuleStatus.code : "UNKNOWN"'
      description: status.APIRuleStatus.desc
  presets: |-
    - name: Default gateway
      default: true
      value:
        spec:
          gateway: kyma-gateway.kyma-system.svc.cluster.local
          rules:
            - path: /.*
              methods:
                - GET
              accessStrategies:
                - handler: allow
  translations: |
    en:
      accessStrategies: Access Strategies
      accessStrategies.config: Config
      accessStrategies.handler: Handler
      accessStrategies.handlers: Handlers
      accessStrategies.jwks_urls: JWKS URLs
      accessStrategies.trusted_issuers: Trusted Issuers
      accessStrategies.required_scope: Required Scope
      accessStrategies.introspection_url: Introspection URL
      accessStrategies.introspection_request_headers: Introspection Request Headers
      accessStrategies.token_from: Token From
      gateway: Gateway
      host: Host
      inputInfo.gateway: Gateway structure, '{GATEWAY}.{NAMESPACE}.svc.cluster.local'
      inputInfo.path: "Path can contain alphanumeric characters and '/', '.', '*', '?', '!', '-', '(', and ')'."
      inputInfo.jwks_urls: "JWKS URLs must start with 'https://', 'http://' or 'file://. HTTP protocol is not recommended."
      inputInfo.trusted_issuers: "Trusted Issuers must start with 'https://', 'http://' or 'file://'"
      inputInfo.introspection_url: "URL endpoint used for validating the Bearer token. Should start with 'http://' or 'https://. HTTP protocol is not recommended.'"
      inputInfo.introspection_request_headers: "Headers sent alongside the introspection request"
      inputInfo.timeout: "Timeout for HTTP requests in seconds. The timeout can be configured for a maximum of 3900 seconds (65 minutes)."
      inputInfo.token_from: "Defines where Ory Oathkeeper should look for access token"
      mutators: Mutators
      mutators.config: Config
      mutators.handlers: Handlers
      path: Path
      rules: Rules
      rules.methods: Methods
      rules.path: Path
      service: Service
      service.name: Name
      service.port: Port
      service-name: Service Name
      status: Status
      general: General
      timeout: HTTP Request Timeout
      details.timeout: HTTP Request Timeout (seconds)
      virtualService: Virtual Service
      alert.spec.host: Host can not be a wildcard, replace * with subdomain name
      alert.spec.jwks_url_http: "JWKS URL: HTTP protocol is not secure, consider using HTTPS"
      alert.spec.trusted_issuers_http: "Trusted Issuers: HTTP protocol is not secure, consider using HTTPS"
