apiVersion: v1
kind: ConfigMap
metadata:
  name: module-wizard
  namespace: kube-public
  labels:
    app.kubernetes.io/name: module-wizard
    busola.io/extension: wizard
    busola.io/extension-version: '0.5'
data:
  dataSources: |
    moduleTemplates:
      resource:
        kind: ModuleTemplate
        namespace: null
        group: operator.kyma-project.io
        version: v1beta1
  general: |
    id: module-wizard
    name: Module Wizard
    description: Add your module.
    resources:
      kyma:
        kind: Kyma
        group: operator.kyma-project.io
        version: v1beta1
  defaults: |
    kyma:
      spec:
        modules:
          - {}
  steps: |
    - name: Kyma Modules
      description: Choose modules you want to install on the cluster.
      resource: kyma
      form:
        - path: spec.channel
          required: true
        - widget: GenericList
          path: spec.modules
          children:
            - path: "[].name"
              required: true
              enum: '$distinct($moduleTemplates().items.metadata.labels."operator.kyma-project.io/module-name")'
            - path: "[].channel"
              required: true
              visibility: "$boolean($item.name)"
              enum: |
                $filter($moduleTemplates().items, function($v) {
                  $v.metadata.labels."operator.kyma-project.io/module-name" = $item.name
                }).spec.channel
        - widget: Alert
          severity: warning
          alert: '"CAUTION: The Service Level Agreements (SLAs) and Support obligations do not apply to Beta modules and functionalities. If Beta modules or functionalities directly or indirectly affect other modules, the Service Level Agreements and Support for these modules are limited to priority levels P3 (Medium) or P4 (Low). Thus, Beta releases are not intended for use in customer production environments."'
          visibility: '(
            $fullModuleTemplate := $filter($moduleTemplates().items, function($v) {
              $v.metadata.labels."operator.kyma-project.io/module-name" in $item.spec.modules.name
            });
            $isBeta := $fullModuleTemplate.metadata.labels."operator.kyma-project.io/beta" = "true";
            $isBeta;
          )'
