apiVersion: v1
kind: ConfigMap
metadata:
  name: module-wizard
  namespace: kube-public
  labels:
    app.kubernetes.io/name: module-wizard
    busola.io/extension: wizard
    busola.io/extension-version: '0.5'
data:
  dataSources: |
    moduleTemplates:
      resource:
        kind: ModuleTemplate
        namespace: null
        group: operator.kyma-project.io
        version: v1alpha1
  general: |
    id: module-wizard
    name: Module Wizard
    description: Now you need to add the module.
    resources:
      kyma:
        kind: Kyma
        group: operator.kyma-project.io
        version: v1beta1
  steps: |
    - name: Kyma Modules
      description: Choose modules which you want to install on the cluster.
      resource: kyma
      form:
        - path: spec.channel
          required: true
        - widget: GenericList
          path: spec.modules
          children:
            - path: "[].name"
              required: true
              enum: '$distinct($moduleTemplates().items.metadata.labels."operator.kyma-project.io/module-name")'
            - path: "[].channel"
              required: true
              visibility: "$boolean($item.name)"
              enum: |
                $filter($moduleTemplates().items, function($v) {
                  $v.metadata.labels."operator.kyma-project.io/module-name" = $item.name
                }).spec.channel
        - widget: Alert
          severity: warning
          alert: '"alert.beta"'
          visibility: '"beta" in $item.spec.modules.channel'
